//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MtHoodMiata.Web", "fkCarDetail_Color", "Color", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MtHoodMiata.Web.Models.Color), "CarDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MtHoodMiata.Web.Models.CarDetail), true)]
[assembly: EdmRelationshipAttribute("MtHoodMiata.Web", "fkCarDetail_Membership", "Membership", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MtHoodMiata.Web.Models.Membership), "CarDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MtHoodMiata.Web.Models.CarDetail), true)]
[assembly: EdmRelationshipAttribute("MtHoodMiata.Web", "fkClassifiedAd_ClassifiedAdType", "ClassifiedAdType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MtHoodMiata.Web.Models.ClassifiedAdType), "ClassifiedAd", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MtHoodMiata.Web.Models.ClassifiedAd), true)]
[assembly: EdmRelationshipAttribute("MtHoodMiata.Web", "fkClassifiedAd_Membership", "Membership", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MtHoodMiata.Web.Models.Membership), "ClassifiedAd", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MtHoodMiata.Web.Models.ClassifiedAd), true)]
[assembly: EdmRelationshipAttribute("MtHoodMiata.Web", "fkColor_ColorFamily", "ColorFamily", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MtHoodMiata.Web.Models.ColorFamily), "Color", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MtHoodMiata.Web.Models.Color), true)]

#endregion

namespace MtHoodMiata.Web.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MtHoodMiataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MtHoodMiataEntities object using the connection string found in the 'MtHoodMiataEntities' section of the application configuration file.
        /// </summary>
        public MtHoodMiataEntities() : base("name=MtHoodMiataEntities", "MtHoodMiataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MtHoodMiataEntities object.
        /// </summary>
        public MtHoodMiataEntities(string connectionString) : base(connectionString, "MtHoodMiataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MtHoodMiataEntities object.
        /// </summary>
        public MtHoodMiataEntities(EntityConnection connection) : base(connection, "MtHoodMiataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CarDetail> CarDetails
        {
            get
            {
                if ((_CarDetails == null))
                {
                    _CarDetails = base.CreateObjectSet<CarDetail>("CarDetails");
                }
                return _CarDetails;
            }
        }
        private ObjectSet<CarDetail> _CarDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClassifiedAd> ClassifiedAds
        {
            get
            {
                if ((_ClassifiedAds == null))
                {
                    _ClassifiedAds = base.CreateObjectSet<ClassifiedAd>("ClassifiedAds");
                }
                return _ClassifiedAds;
            }
        }
        private ObjectSet<ClassifiedAd> _ClassifiedAds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClassifiedAdType> ClassifiedAdTypes
        {
            get
            {
                if ((_ClassifiedAdTypes == null))
                {
                    _ClassifiedAdTypes = base.CreateObjectSet<ClassifiedAdType>("ClassifiedAdTypes");
                }
                return _ClassifiedAdTypes;
            }
        }
        private ObjectSet<ClassifiedAdType> _ClassifiedAdTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Color> Colors
        {
            get
            {
                if ((_Colors == null))
                {
                    _Colors = base.CreateObjectSet<Color>("Colors");
                }
                return _Colors;
            }
        }
        private ObjectSet<Color> _Colors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ColorFamily> ColorFamilies
        {
            get
            {
                if ((_ColorFamilies == null))
                {
                    _ColorFamilies = base.CreateObjectSet<ColorFamily>("ColorFamilies");
                }
                return _ColorFamilies;
            }
        }
        private ObjectSet<ColorFamily> _ColorFamilies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EventInfo> EventInfoes
        {
            get
            {
                if ((_EventInfoes == null))
                {
                    _EventInfoes = base.CreateObjectSet<EventInfo>("EventInfoes");
                }
                return _EventInfoes;
            }
        }
        private ObjectSet<EventInfo> _EventInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MeetingInfo> MeetingInfoes
        {
            get
            {
                if ((_MeetingInfoes == null))
                {
                    _MeetingInfoes = base.CreateObjectSet<MeetingInfo>("MeetingInfoes");
                }
                return _MeetingInfoes;
            }
        }
        private ObjectSet<MeetingInfo> _MeetingInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Membership> Memberships
        {
            get
            {
                if ((_Memberships == null))
                {
                    _Memberships = base.CreateObjectSet<Membership>("Memberships");
                }
                return _Memberships;
            }
        }
        private ObjectSet<Membership> _Memberships;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CarDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCarDetails(CarDetail carDetail)
        {
            base.AddObject("CarDetails", carDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClassifiedAds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClassifiedAds(ClassifiedAd classifiedAd)
        {
            base.AddObject("ClassifiedAds", classifiedAd);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClassifiedAdTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClassifiedAdTypes(ClassifiedAdType classifiedAdType)
        {
            base.AddObject("ClassifiedAdTypes", classifiedAdType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Colors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToColors(Color color)
        {
            base.AddObject("Colors", color);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ColorFamilies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToColorFamilies(ColorFamily colorFamily)
        {
            base.AddObject("ColorFamilies", colorFamily);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EventInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEventInfoes(EventInfo eventInfo)
        {
            base.AddObject("EventInfoes", eventInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MeetingInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMeetingInfoes(MeetingInfo meetingInfo)
        {
            base.AddObject("MeetingInfoes", meetingInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Memberships EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMemberships(Membership membership)
        {
            base.AddObject("Memberships", membership);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MtHoodMiata.Web", Name="CarDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CarDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CarDetail object.
        /// </summary>
        /// <param name="carDetailId">Initial value of the CarDetailId property.</param>
        /// <param name="membershipId">Initial value of the MembershipId property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="specialEdition">Initial value of the SpecialEdition property.</param>
        /// <param name="colorId">Initial value of the ColorId property.</param>
        public static CarDetail CreateCarDetail(global::System.Int32 carDetailId, global::System.Int32 membershipId, global::System.String year, global::System.Boolean specialEdition, global::System.Int32 colorId)
        {
            CarDetail carDetail = new CarDetail();
            carDetail.CarDetailId = carDetailId;
            carDetail.MembershipId = membershipId;
            carDetail.Year = year;
            carDetail.SpecialEdition = specialEdition;
            carDetail.ColorId = colorId;
            return carDetail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CarDetailId
        {
            get
            {
                return _CarDetailId;
            }
            set
            {
                if (_CarDetailId != value)
                {
                    OnCarDetailIdChanging(value);
                    ReportPropertyChanging("CarDetailId");
                    _CarDetailId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CarDetailId");
                    OnCarDetailIdChanged();
                }
            }
        }
        private global::System.Int32 _CarDetailId;
        partial void OnCarDetailIdChanging(global::System.Int32 value);
        partial void OnCarDetailIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MembershipId
        {
            get
            {
                return _MembershipId;
            }
            set
            {
                OnMembershipIdChanging(value);
                ReportPropertyChanging("MembershipId");
                _MembershipId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MembershipId");
                OnMembershipIdChanged();
            }
        }
        private global::System.Int32 _MembershipId;
        partial void OnMembershipIdChanging(global::System.Int32 value);
        partial void OnMembershipIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.String _Year;
        partial void OnYearChanging(global::System.String value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nickname
        {
            get
            {
                return _Nickname;
            }
            set
            {
                OnNicknameChanging(value);
                ReportPropertyChanging("Nickname");
                _Nickname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nickname");
                OnNicknameChanged();
            }
        }
        private global::System.String _Nickname;
        partial void OnNicknameChanging(global::System.String value);
        partial void OnNicknameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String License
        {
            get
            {
                return _License;
            }
            set
            {
                OnLicenseChanging(value);
                ReportPropertyChanging("License");
                _License = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("License");
                OnLicenseChanged();
            }
        }
        private global::System.String _License;
        partial void OnLicenseChanging(global::System.String value);
        partial void OnLicenseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mods
        {
            get
            {
                return _Mods;
            }
            set
            {
                OnModsChanging(value);
                ReportPropertyChanging("Mods");
                _Mods = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mods");
                OnModsChanged();
            }
        }
        private global::System.String _Mods;
        partial void OnModsChanging(global::System.String value);
        partial void OnModsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SpecialEdition
        {
            get
            {
                return _SpecialEdition;
            }
            set
            {
                OnSpecialEditionChanging(value);
                ReportPropertyChanging("SpecialEdition");
                _SpecialEdition = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SpecialEdition");
                OnSpecialEditionChanged();
            }
        }
        private global::System.Boolean _SpecialEdition;
        partial void OnSpecialEditionChanging(global::System.Boolean value);
        partial void OnSpecialEditionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ColorId
        {
            get
            {
                return _ColorId;
            }
            set
            {
                OnColorIdChanging(value);
                ReportPropertyChanging("ColorId");
                _ColorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ColorId");
                OnColorIdChanged();
            }
        }
        private global::System.Int32 _ColorId;
        partial void OnColorIdChanging(global::System.Int32 value);
        partial void OnColorIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MtHoodMiata.Web", "fkCarDetail_Color", "Color")]
        public Color Color
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Color>("MtHoodMiata.Web.fkCarDetail_Color", "Color").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Color>("MtHoodMiata.Web.fkCarDetail_Color", "Color").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Color> ColorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Color>("MtHoodMiata.Web.fkCarDetail_Color", "Color");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Color>("MtHoodMiata.Web.fkCarDetail_Color", "Color", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MtHoodMiata.Web", "fkCarDetail_Membership", "Membership")]
        public Membership Membership
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Membership>("MtHoodMiata.Web.fkCarDetail_Membership", "Membership").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Membership>("MtHoodMiata.Web.fkCarDetail_Membership", "Membership").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Membership> MembershipReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Membership>("MtHoodMiata.Web.fkCarDetail_Membership", "Membership");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Membership>("MtHoodMiata.Web.fkCarDetail_Membership", "Membership", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MtHoodMiata.Web", Name="ClassifiedAd")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClassifiedAd : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClassifiedAd object.
        /// </summary>
        /// <param name="classifiedAdId">Initial value of the ClassifiedAdId property.</param>
        /// <param name="membershipId">Initial value of the MembershipId property.</param>
        /// <param name="classifiedAdTypeCode">Initial value of the ClassifiedAdTypeCode property.</param>
        /// <param name="adText">Initial value of the AdText property.</param>
        /// <param name="adPlacedDttm">Initial value of the AdPlacedDttm property.</param>
        public static ClassifiedAd CreateClassifiedAd(global::System.Int32 classifiedAdId, global::System.Int32 membershipId, global::System.Int32 classifiedAdTypeCode, global::System.String adText, global::System.DateTime adPlacedDttm)
        {
            ClassifiedAd classifiedAd = new ClassifiedAd();
            classifiedAd.ClassifiedAdId = classifiedAdId;
            classifiedAd.MembershipId = membershipId;
            classifiedAd.ClassifiedAdTypeCode = classifiedAdTypeCode;
            classifiedAd.AdText = adText;
            classifiedAd.AdPlacedDttm = adPlacedDttm;
            return classifiedAd;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClassifiedAdId
        {
            get
            {
                return _ClassifiedAdId;
            }
            set
            {
                if (_ClassifiedAdId != value)
                {
                    OnClassifiedAdIdChanging(value);
                    ReportPropertyChanging("ClassifiedAdId");
                    _ClassifiedAdId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClassifiedAdId");
                    OnClassifiedAdIdChanged();
                }
            }
        }
        private global::System.Int32 _ClassifiedAdId;
        partial void OnClassifiedAdIdChanging(global::System.Int32 value);
        partial void OnClassifiedAdIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MembershipId
        {
            get
            {
                return _MembershipId;
            }
            set
            {
                OnMembershipIdChanging(value);
                ReportPropertyChanging("MembershipId");
                _MembershipId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MembershipId");
                OnMembershipIdChanged();
            }
        }
        private global::System.Int32 _MembershipId;
        partial void OnMembershipIdChanging(global::System.Int32 value);
        partial void OnMembershipIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClassifiedAdTypeCode
        {
            get
            {
                return _ClassifiedAdTypeCode;
            }
            set
            {
                OnClassifiedAdTypeCodeChanging(value);
                ReportPropertyChanging("ClassifiedAdTypeCode");
                _ClassifiedAdTypeCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassifiedAdTypeCode");
                OnClassifiedAdTypeCodeChanged();
            }
        }
        private global::System.Int32 _ClassifiedAdTypeCode;
        partial void OnClassifiedAdTypeCodeChanging(global::System.Int32 value);
        partial void OnClassifiedAdTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AdText
        {
            get
            {
                return _AdText;
            }
            set
            {
                OnAdTextChanging(value);
                ReportPropertyChanging("AdText");
                _AdText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AdText");
                OnAdTextChanged();
            }
        }
        private global::System.String _AdText;
        partial void OnAdTextChanging(global::System.String value);
        partial void OnAdTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AdPlacedDttm
        {
            get
            {
                return _AdPlacedDttm;
            }
            set
            {
                OnAdPlacedDttmChanging(value);
                ReportPropertyChanging("AdPlacedDttm");
                _AdPlacedDttm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AdPlacedDttm");
                OnAdPlacedDttmChanged();
            }
        }
        private global::System.DateTime _AdPlacedDttm;
        partial void OnAdPlacedDttmChanging(global::System.DateTime value);
        partial void OnAdPlacedDttmChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MtHoodMiata.Web", "fkClassifiedAd_ClassifiedAdType", "ClassifiedAdType")]
        public ClassifiedAdType ClassifiedAdType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClassifiedAdType>("MtHoodMiata.Web.fkClassifiedAd_ClassifiedAdType", "ClassifiedAdType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClassifiedAdType>("MtHoodMiata.Web.fkClassifiedAd_ClassifiedAdType", "ClassifiedAdType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ClassifiedAdType> ClassifiedAdTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClassifiedAdType>("MtHoodMiata.Web.fkClassifiedAd_ClassifiedAdType", "ClassifiedAdType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ClassifiedAdType>("MtHoodMiata.Web.fkClassifiedAd_ClassifiedAdType", "ClassifiedAdType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MtHoodMiata.Web", "fkClassifiedAd_Membership", "Membership")]
        public Membership Membership
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Membership>("MtHoodMiata.Web.fkClassifiedAd_Membership", "Membership").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Membership>("MtHoodMiata.Web.fkClassifiedAd_Membership", "Membership").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Membership> MembershipReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Membership>("MtHoodMiata.Web.fkClassifiedAd_Membership", "Membership");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Membership>("MtHoodMiata.Web.fkClassifiedAd_Membership", "Membership", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MtHoodMiata.Web", Name="ClassifiedAdType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClassifiedAdType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClassifiedAdType object.
        /// </summary>
        /// <param name="classifiedAdTypeCode">Initial value of the ClassifiedAdTypeCode property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="sequence">Initial value of the Sequence property.</param>
        public static ClassifiedAdType CreateClassifiedAdType(global::System.Int32 classifiedAdTypeCode, global::System.String name, global::System.Int32 sequence)
        {
            ClassifiedAdType classifiedAdType = new ClassifiedAdType();
            classifiedAdType.ClassifiedAdTypeCode = classifiedAdTypeCode;
            classifiedAdType.Name = name;
            classifiedAdType.Sequence = sequence;
            return classifiedAdType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClassifiedAdTypeCode
        {
            get
            {
                return _ClassifiedAdTypeCode;
            }
            set
            {
                if (_ClassifiedAdTypeCode != value)
                {
                    OnClassifiedAdTypeCodeChanging(value);
                    ReportPropertyChanging("ClassifiedAdTypeCode");
                    _ClassifiedAdTypeCode = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClassifiedAdTypeCode");
                    OnClassifiedAdTypeCodeChanged();
                }
            }
        }
        private global::System.Int32 _ClassifiedAdTypeCode;
        partial void OnClassifiedAdTypeCodeChanging(global::System.Int32 value);
        partial void OnClassifiedAdTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sequence
        {
            get
            {
                return _Sequence;
            }
            set
            {
                OnSequenceChanging(value);
                ReportPropertyChanging("Sequence");
                _Sequence = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sequence");
                OnSequenceChanged();
            }
        }
        private global::System.Int32 _Sequence;
        partial void OnSequenceChanging(global::System.Int32 value);
        partial void OnSequenceChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MtHoodMiata.Web", "fkClassifiedAd_ClassifiedAdType", "ClassifiedAd")]
        public EntityCollection<ClassifiedAd> ClassifiedAds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClassifiedAd>("MtHoodMiata.Web.fkClassifiedAd_ClassifiedAdType", "ClassifiedAd");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClassifiedAd>("MtHoodMiata.Web.fkClassifiedAd_ClassifiedAdType", "ClassifiedAd", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MtHoodMiata.Web", Name="Color")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Color : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Color object.
        /// </summary>
        /// <param name="colorId">Initial value of the ColorId property.</param>
        /// <param name="colorName">Initial value of the ColorName property.</param>
        /// <param name="colorFamilyId">Initial value of the ColorFamilyId property.</param>
        public static Color CreateColor(global::System.Int32 colorId, global::System.String colorName, global::System.Int32 colorFamilyId)
        {
            Color color = new Color();
            color.ColorId = colorId;
            color.ColorName = colorName;
            color.ColorFamilyId = colorFamilyId;
            return color;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ColorId
        {
            get
            {
                return _ColorId;
            }
            set
            {
                if (_ColorId != value)
                {
                    OnColorIdChanging(value);
                    ReportPropertyChanging("ColorId");
                    _ColorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ColorId");
                    OnColorIdChanged();
                }
            }
        }
        private global::System.Int32 _ColorId;
        partial void OnColorIdChanging(global::System.Int32 value);
        partial void OnColorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ColorName
        {
            get
            {
                return _ColorName;
            }
            set
            {
                OnColorNameChanging(value);
                ReportPropertyChanging("ColorName");
                _ColorName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ColorName");
                OnColorNameChanged();
            }
        }
        private global::System.String _ColorName;
        partial void OnColorNameChanging(global::System.String value);
        partial void OnColorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ColorFamilyId
        {
            get
            {
                return _ColorFamilyId;
            }
            set
            {
                OnColorFamilyIdChanging(value);
                ReportPropertyChanging("ColorFamilyId");
                _ColorFamilyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ColorFamilyId");
                OnColorFamilyIdChanged();
            }
        }
        private global::System.Int32 _ColorFamilyId;
        partial void OnColorFamilyIdChanging(global::System.Int32 value);
        partial void OnColorFamilyIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MtHoodMiata.Web", "fkCarDetail_Color", "CarDetail")]
        public EntityCollection<CarDetail> CarDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CarDetail>("MtHoodMiata.Web.fkCarDetail_Color", "CarDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CarDetail>("MtHoodMiata.Web.fkCarDetail_Color", "CarDetail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MtHoodMiata.Web", "fkColor_ColorFamily", "ColorFamily")]
        public ColorFamily ColorFamily
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ColorFamily>("MtHoodMiata.Web.fkColor_ColorFamily", "ColorFamily").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ColorFamily>("MtHoodMiata.Web.fkColor_ColorFamily", "ColorFamily").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ColorFamily> ColorFamilyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ColorFamily>("MtHoodMiata.Web.fkColor_ColorFamily", "ColorFamily");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ColorFamily>("MtHoodMiata.Web.fkColor_ColorFamily", "ColorFamily", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MtHoodMiata.Web", Name="ColorFamily")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ColorFamily : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ColorFamily object.
        /// </summary>
        /// <param name="colorFamilyId">Initial value of the ColorFamilyId property.</param>
        /// <param name="colorFamilyName">Initial value of the ColorFamilyName property.</param>
        public static ColorFamily CreateColorFamily(global::System.Int32 colorFamilyId, global::System.String colorFamilyName)
        {
            ColorFamily colorFamily = new ColorFamily();
            colorFamily.ColorFamilyId = colorFamilyId;
            colorFamily.ColorFamilyName = colorFamilyName;
            return colorFamily;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ColorFamilyId
        {
            get
            {
                return _ColorFamilyId;
            }
            set
            {
                if (_ColorFamilyId != value)
                {
                    OnColorFamilyIdChanging(value);
                    ReportPropertyChanging("ColorFamilyId");
                    _ColorFamilyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ColorFamilyId");
                    OnColorFamilyIdChanged();
                }
            }
        }
        private global::System.Int32 _ColorFamilyId;
        partial void OnColorFamilyIdChanging(global::System.Int32 value);
        partial void OnColorFamilyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ColorFamilyName
        {
            get
            {
                return _ColorFamilyName;
            }
            set
            {
                OnColorFamilyNameChanging(value);
                ReportPropertyChanging("ColorFamilyName");
                _ColorFamilyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ColorFamilyName");
                OnColorFamilyNameChanged();
            }
        }
        private global::System.String _ColorFamilyName;
        partial void OnColorFamilyNameChanging(global::System.String value);
        partial void OnColorFamilyNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MtHoodMiata.Web", "fkColor_ColorFamily", "Color")]
        public EntityCollection<Color> Colors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Color>("MtHoodMiata.Web.fkColor_ColorFamily", "Color");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Color>("MtHoodMiata.Web.fkColor_ColorFamily", "Color", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MtHoodMiata.Web", Name="EventInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EventInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EventInfo object.
        /// </summary>
        /// <param name="eventId">Initial value of the EventId property.</param>
        /// <param name="eventName">Initial value of the EventName property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        /// <param name="planner">Initial value of the Planner property.</param>
        /// <param name="updatedDttm">Initial value of the UpdatedDttm property.</param>
        public static EventInfo CreateEventInfo(global::System.Int32 eventId, global::System.String eventName, global::System.DateTime startDate, global::System.DateTime endDate, global::System.String planner, global::System.DateTime updatedDttm)
        {
            EventInfo eventInfo = new EventInfo();
            eventInfo.EventId = eventId;
            eventInfo.EventName = eventName;
            eventInfo.StartDate = startDate;
            eventInfo.EndDate = endDate;
            eventInfo.Planner = planner;
            eventInfo.UpdatedDttm = updatedDttm;
            return eventInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventId
        {
            get
            {
                return _EventId;
            }
            set
            {
                if (_EventId != value)
                {
                    OnEventIdChanging(value);
                    ReportPropertyChanging("EventId");
                    _EventId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EventId");
                    OnEventIdChanged();
                }
            }
        }
        private global::System.Int32 _EventId;
        partial void OnEventIdChanging(global::System.Int32 value);
        partial void OnEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EventName
        {
            get
            {
                return _EventName;
            }
            set
            {
                OnEventNameChanging(value);
                ReportPropertyChanging("EventName");
                _EventName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EventName");
                OnEventNameChanged();
            }
        }
        private global::System.String _EventName;
        partial void OnEventNameChanging(global::System.String value);
        partial void OnEventNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Planner
        {
            get
            {
                return _Planner;
            }
            set
            {
                OnPlannerChanging(value);
                ReportPropertyChanging("Planner");
                _Planner = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Planner");
                OnPlannerChanged();
            }
        }
        private global::System.String _Planner;
        partial void OnPlannerChanging(global::System.String value);
        partial void OnPlannerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedDttm
        {
            get
            {
                return _UpdatedDttm;
            }
            set
            {
                OnUpdatedDttmChanging(value);
                ReportPropertyChanging("UpdatedDttm");
                _UpdatedDttm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDttm");
                OnUpdatedDttmChanged();
            }
        }
        private global::System.DateTime _UpdatedDttm;
        partial void OnUpdatedDttmChanging(global::System.DateTime value);
        partial void OnUpdatedDttmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventDetails
        {
            get
            {
                return _EventDetails;
            }
            set
            {
                OnEventDetailsChanging(value);
                ReportPropertyChanging("EventDetails");
                _EventDetails = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventDetails");
                OnEventDetailsChanged();
            }
        }
        private global::System.String _EventDetails;
        partial void OnEventDetailsChanging(global::System.String value);
        partial void OnEventDetailsChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MtHoodMiata.Web", Name="MeetingInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MeetingInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MeetingInfo object.
        /// </summary>
        /// <param name="meetingId">Initial value of the MeetingId property.</param>
        /// <param name="location">Initial value of the Location property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="mapUrl">Initial value of the MapUrl property.</param>
        /// <param name="meetingDate">Initial value of the MeetingDate property.</param>
        /// <param name="updatedDttm">Initial value of the UpdatedDttm property.</param>
        public static MeetingInfo CreateMeetingInfo(global::System.Int32 meetingId, global::System.String location, global::System.String address, global::System.String city, global::System.String state, global::System.String mapUrl, global::System.DateTime meetingDate, global::System.DateTime updatedDttm)
        {
            MeetingInfo meetingInfo = new MeetingInfo();
            meetingInfo.MeetingId = meetingId;
            meetingInfo.Location = location;
            meetingInfo.Address = address;
            meetingInfo.City = city;
            meetingInfo.State = state;
            meetingInfo.MapUrl = mapUrl;
            meetingInfo.MeetingDate = meetingDate;
            meetingInfo.UpdatedDttm = updatedDttm;
            return meetingInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MeetingId
        {
            get
            {
                return _MeetingId;
            }
            set
            {
                if (_MeetingId != value)
                {
                    OnMeetingIdChanging(value);
                    ReportPropertyChanging("MeetingId");
                    _MeetingId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MeetingId");
                    OnMeetingIdChanged();
                }
            }
        }
        private global::System.Int32 _MeetingId;
        partial void OnMeetingIdChanging(global::System.Int32 value);
        partial void OnMeetingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MapUrl
        {
            get
            {
                return _MapUrl;
            }
            set
            {
                OnMapUrlChanging(value);
                ReportPropertyChanging("MapUrl");
                _MapUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MapUrl");
                OnMapUrlChanged();
            }
        }
        private global::System.String _MapUrl;
        partial void OnMapUrlChanging(global::System.String value);
        partial void OnMapUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MeetingDate
        {
            get
            {
                return _MeetingDate;
            }
            set
            {
                OnMeetingDateChanging(value);
                ReportPropertyChanging("MeetingDate");
                _MeetingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MeetingDate");
                OnMeetingDateChanged();
            }
        }
        private global::System.DateTime _MeetingDate;
        partial void OnMeetingDateChanging(global::System.DateTime value);
        partial void OnMeetingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedDttm
        {
            get
            {
                return _UpdatedDttm;
            }
            set
            {
                OnUpdatedDttmChanging(value);
                ReportPropertyChanging("UpdatedDttm");
                _UpdatedDttm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDttm");
                OnUpdatedDttmChanged();
            }
        }
        private global::System.DateTime _UpdatedDttm;
        partial void OnUpdatedDttmChanging(global::System.DateTime value);
        partial void OnUpdatedDttmChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MtHoodMiata.Web", Name="Membership")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Membership : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Membership object.
        /// </summary>
        /// <param name="membershipId">Initial value of the MembershipId property.</param>
        /// <param name="membershipDueDate">Initial value of the MembershipDueDate property.</param>
        /// <param name="newsletterPreference">Initial value of the NewsletterPreference property.</param>
        /// <param name="showInRoster">Initial value of the ShowInRoster property.</param>
        /// <param name="member1FirstName">Initial value of the Member1FirstName property.</param>
        /// <param name="member1LastName">Initial value of the Member1LastName property.</param>
        /// <param name="member1Username">Initial value of the Member1Username property.</param>
        /// <param name="member1Password">Initial value of the Member1Password property.</param>
        /// <param name="isMember1BoardMember">Initial value of the IsMember1BoardMember property.</param>
        /// <param name="isMember2BoardMember">Initial value of the IsMember2BoardMember property.</param>
        /// <param name="addressLine1">Initial value of the AddressLine1 property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="zip">Initial value of the Zip property.</param>
        public static Membership CreateMembership(global::System.Int32 membershipId, global::System.DateTime membershipDueDate, global::System.String newsletterPreference, global::System.Boolean showInRoster, global::System.String member1FirstName, global::System.String member1LastName, global::System.String member1Username, global::System.String member1Password, global::System.Boolean isMember1BoardMember, global::System.Boolean isMember2BoardMember, global::System.String addressLine1, global::System.String city, global::System.String state, global::System.String zip)
        {
            Membership membership = new Membership();
            membership.MembershipId = membershipId;
            membership.MembershipDueDate = membershipDueDate;
            membership.NewsletterPreference = newsletterPreference;
            membership.ShowInRoster = showInRoster;
            membership.Member1FirstName = member1FirstName;
            membership.Member1LastName = member1LastName;
            membership.Member1Username = member1Username;
            membership.Member1Password = member1Password;
            membership.IsMember1BoardMember = isMember1BoardMember;
            membership.IsMember2BoardMember = isMember2BoardMember;
            membership.AddressLine1 = addressLine1;
            membership.City = city;
            membership.State = state;
            membership.Zip = zip;
            return membership;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MembershipId
        {
            get
            {
                return _MembershipId;
            }
            set
            {
                if (_MembershipId != value)
                {
                    OnMembershipIdChanging(value);
                    ReportPropertyChanging("MembershipId");
                    _MembershipId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MembershipId");
                    OnMembershipIdChanged();
                }
            }
        }
        private global::System.Int32 _MembershipId;
        partial void OnMembershipIdChanging(global::System.Int32 value);
        partial void OnMembershipIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MembershipDueDate
        {
            get
            {
                return _MembershipDueDate;
            }
            set
            {
                OnMembershipDueDateChanging(value);
                ReportPropertyChanging("MembershipDueDate");
                _MembershipDueDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MembershipDueDate");
                OnMembershipDueDateChanged();
            }
        }
        private global::System.DateTime _MembershipDueDate;
        partial void OnMembershipDueDateChanging(global::System.DateTime value);
        partial void OnMembershipDueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NewsletterPreference
        {
            get
            {
                return _NewsletterPreference;
            }
            set
            {
                OnNewsletterPreferenceChanging(value);
                ReportPropertyChanging("NewsletterPreference");
                _NewsletterPreference = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NewsletterPreference");
                OnNewsletterPreferenceChanged();
            }
        }
        private global::System.String _NewsletterPreference;
        partial void OnNewsletterPreferenceChanging(global::System.String value);
        partial void OnNewsletterPreferenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ShowInRoster
        {
            get
            {
                return _ShowInRoster;
            }
            set
            {
                OnShowInRosterChanging(value);
                ReportPropertyChanging("ShowInRoster");
                _ShowInRoster = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShowInRoster");
                OnShowInRosterChanged();
            }
        }
        private global::System.Boolean _ShowInRoster;
        partial void OnShowInRosterChanging(global::System.Boolean value);
        partial void OnShowInRosterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Member1FirstName
        {
            get
            {
                return _Member1FirstName;
            }
            set
            {
                OnMember1FirstNameChanging(value);
                ReportPropertyChanging("Member1FirstName");
                _Member1FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Member1FirstName");
                OnMember1FirstNameChanged();
            }
        }
        private global::System.String _Member1FirstName;
        partial void OnMember1FirstNameChanging(global::System.String value);
        partial void OnMember1FirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Member1LastName
        {
            get
            {
                return _Member1LastName;
            }
            set
            {
                OnMember1LastNameChanging(value);
                ReportPropertyChanging("Member1LastName");
                _Member1LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Member1LastName");
                OnMember1LastNameChanged();
            }
        }
        private global::System.String _Member1LastName;
        partial void OnMember1LastNameChanging(global::System.String value);
        partial void OnMember1LastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Member1CellPhone
        {
            get
            {
                return _Member1CellPhone;
            }
            set
            {
                OnMember1CellPhoneChanging(value);
                ReportPropertyChanging("Member1CellPhone");
                _Member1CellPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Member1CellPhone");
                OnMember1CellPhoneChanged();
            }
        }
        private global::System.String _Member1CellPhone;
        partial void OnMember1CellPhoneChanging(global::System.String value);
        partial void OnMember1CellPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Member1WorkPhone
        {
            get
            {
                return _Member1WorkPhone;
            }
            set
            {
                OnMember1WorkPhoneChanging(value);
                ReportPropertyChanging("Member1WorkPhone");
                _Member1WorkPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Member1WorkPhone");
                OnMember1WorkPhoneChanged();
            }
        }
        private global::System.String _Member1WorkPhone;
        partial void OnMember1WorkPhoneChanging(global::System.String value);
        partial void OnMember1WorkPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Member1Dob
        {
            get
            {
                return _Member1Dob;
            }
            set
            {
                OnMember1DobChanging(value);
                ReportPropertyChanging("Member1Dob");
                _Member1Dob = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Member1Dob");
                OnMember1DobChanged();
            }
        }
        private global::System.String _Member1Dob;
        partial void OnMember1DobChanging(global::System.String value);
        partial void OnMember1DobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Member1Username
        {
            get
            {
                return _Member1Username;
            }
            set
            {
                OnMember1UsernameChanging(value);
                ReportPropertyChanging("Member1Username");
                _Member1Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Member1Username");
                OnMember1UsernameChanged();
            }
        }
        private global::System.String _Member1Username;
        partial void OnMember1UsernameChanging(global::System.String value);
        partial void OnMember1UsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Member1Password
        {
            get
            {
                return _Member1Password;
            }
            set
            {
                OnMember1PasswordChanging(value);
                ReportPropertyChanging("Member1Password");
                _Member1Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Member1Password");
                OnMember1PasswordChanged();
            }
        }
        private global::System.String _Member1Password;
        partial void OnMember1PasswordChanging(global::System.String value);
        partial void OnMember1PasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Member1Email
        {
            get
            {
                return _Member1Email;
            }
            set
            {
                OnMember1EmailChanging(value);
                ReportPropertyChanging("Member1Email");
                _Member1Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Member1Email");
                OnMember1EmailChanged();
            }
        }
        private global::System.String _Member1Email;
        partial void OnMember1EmailChanging(global::System.String value);
        partial void OnMember1EmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsMember1BoardMember
        {
            get
            {
                return _IsMember1BoardMember;
            }
            set
            {
                OnIsMember1BoardMemberChanging(value);
                ReportPropertyChanging("IsMember1BoardMember");
                _IsMember1BoardMember = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMember1BoardMember");
                OnIsMember1BoardMemberChanged();
            }
        }
        private global::System.Boolean _IsMember1BoardMember;
        partial void OnIsMember1BoardMemberChanging(global::System.Boolean value);
        partial void OnIsMember1BoardMemberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Member2FirstName
        {
            get
            {
                return _Member2FirstName;
            }
            set
            {
                OnMember2FirstNameChanging(value);
                ReportPropertyChanging("Member2FirstName");
                _Member2FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Member2FirstName");
                OnMember2FirstNameChanged();
            }
        }
        private global::System.String _Member2FirstName;
        partial void OnMember2FirstNameChanging(global::System.String value);
        partial void OnMember2FirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Member2LastName
        {
            get
            {
                return _Member2LastName;
            }
            set
            {
                OnMember2LastNameChanging(value);
                ReportPropertyChanging("Member2LastName");
                _Member2LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Member2LastName");
                OnMember2LastNameChanged();
            }
        }
        private global::System.String _Member2LastName;
        partial void OnMember2LastNameChanging(global::System.String value);
        partial void OnMember2LastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Member2CellPhone
        {
            get
            {
                return _Member2CellPhone;
            }
            set
            {
                OnMember2CellPhoneChanging(value);
                ReportPropertyChanging("Member2CellPhone");
                _Member2CellPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Member2CellPhone");
                OnMember2CellPhoneChanged();
            }
        }
        private global::System.String _Member2CellPhone;
        partial void OnMember2CellPhoneChanging(global::System.String value);
        partial void OnMember2CellPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Member2WorkPhone
        {
            get
            {
                return _Member2WorkPhone;
            }
            set
            {
                OnMember2WorkPhoneChanging(value);
                ReportPropertyChanging("Member2WorkPhone");
                _Member2WorkPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Member2WorkPhone");
                OnMember2WorkPhoneChanged();
            }
        }
        private global::System.String _Member2WorkPhone;
        partial void OnMember2WorkPhoneChanging(global::System.String value);
        partial void OnMember2WorkPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Member2Dob
        {
            get
            {
                return _Member2Dob;
            }
            set
            {
                OnMember2DobChanging(value);
                ReportPropertyChanging("Member2Dob");
                _Member2Dob = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Member2Dob");
                OnMember2DobChanged();
            }
        }
        private global::System.String _Member2Dob;
        partial void OnMember2DobChanging(global::System.String value);
        partial void OnMember2DobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Member2Username
        {
            get
            {
                return _Member2Username;
            }
            set
            {
                OnMember2UsernameChanging(value);
                ReportPropertyChanging("Member2Username");
                _Member2Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Member2Username");
                OnMember2UsernameChanged();
            }
        }
        private global::System.String _Member2Username;
        partial void OnMember2UsernameChanging(global::System.String value);
        partial void OnMember2UsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Member2Password
        {
            get
            {
                return _Member2Password;
            }
            set
            {
                OnMember2PasswordChanging(value);
                ReportPropertyChanging("Member2Password");
                _Member2Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Member2Password");
                OnMember2PasswordChanged();
            }
        }
        private global::System.String _Member2Password;
        partial void OnMember2PasswordChanging(global::System.String value);
        partial void OnMember2PasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Member2Email
        {
            get
            {
                return _Member2Email;
            }
            set
            {
                OnMember2EmailChanging(value);
                ReportPropertyChanging("Member2Email");
                _Member2Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Member2Email");
                OnMember2EmailChanged();
            }
        }
        private global::System.String _Member2Email;
        partial void OnMember2EmailChanging(global::System.String value);
        partial void OnMember2EmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsMember2BoardMember
        {
            get
            {
                return _IsMember2BoardMember;
            }
            set
            {
                OnIsMember2BoardMemberChanging(value);
                ReportPropertyChanging("IsMember2BoardMember");
                _IsMember2BoardMember = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMember2BoardMember");
                OnIsMember2BoardMemberChanged();
            }
        }
        private global::System.Boolean _IsMember2BoardMember;
        partial void OnIsMember2BoardMemberChanging(global::System.Boolean value);
        partial void OnIsMember2BoardMemberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddressLine1
        {
            get
            {
                return _AddressLine1;
            }
            set
            {
                OnAddressLine1Changing(value);
                ReportPropertyChanging("AddressLine1");
                _AddressLine1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddressLine1");
                OnAddressLine1Changed();
            }
        }
        private global::System.String _AddressLine1;
        partial void OnAddressLine1Changing(global::System.String value);
        partial void OnAddressLine1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddressLine2
        {
            get
            {
                return _AddressLine2;
            }
            set
            {
                OnAddressLine2Changing(value);
                ReportPropertyChanging("AddressLine2");
                _AddressLine2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddressLine2");
                OnAddressLine2Changed();
            }
        }
        private global::System.String _AddressLine2;
        partial void OnAddressLine2Changing(global::System.String value);
        partial void OnAddressLine2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomePhone
        {
            get
            {
                return _HomePhone;
            }
            set
            {
                OnHomePhoneChanging(value);
                ReportPropertyChanging("HomePhone");
                _HomePhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomePhone");
                OnHomePhoneChanged();
            }
        }
        private global::System.String _HomePhone;
        partial void OnHomePhoneChanging(global::System.String value);
        partial void OnHomePhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AnniversaryDate
        {
            get
            {
                return _AnniversaryDate;
            }
            set
            {
                OnAnniversaryDateChanging(value);
                ReportPropertyChanging("AnniversaryDate");
                _AnniversaryDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AnniversaryDate");
                OnAnniversaryDateChanged();
            }
        }
        private global::System.String _AnniversaryDate;
        partial void OnAnniversaryDateChanging(global::System.String value);
        partial void OnAnniversaryDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MtHoodMiata.Web", "fkCarDetail_Membership", "CarDetail")]
        public EntityCollection<CarDetail> CarDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CarDetail>("MtHoodMiata.Web.fkCarDetail_Membership", "CarDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CarDetail>("MtHoodMiata.Web.fkCarDetail_Membership", "CarDetail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MtHoodMiata.Web", "fkClassifiedAd_Membership", "ClassifiedAd")]
        public EntityCollection<ClassifiedAd> ClassifiedAds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClassifiedAd>("MtHoodMiata.Web.fkClassifiedAd_Membership", "ClassifiedAd");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClassifiedAd>("MtHoodMiata.Web.fkClassifiedAd_Membership", "ClassifiedAd", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
